CREATE TABLE T_BP_PROCESS
(
    UIDPK_ VARCHAR(128) PRIMARY KEY NOT NULL,
    PROC_DEF_ID_ VARCHAR(128) NOT NULL,
    PROC_INST_ID_ VARCHAR(128),
    STATUS_ VARCHAR(16) NOT NULL,
    TYPE_ VARCHAR(64) NOT NULL,
    CREATE_BY_ VARCHAR(64) NOT NULL,
    CREATE_TIME_ TIMESTAMP NOT NULL,
    START_TIME_ TIMESTAMP NULL DEFAULT NULL ,
    END_TIME_ TIMESTAMP NULL DEFAULT NULL
);
CREATE INDEX IDX_PROCESS_ID ON T_BP_PROCESS (PROC_INST_ID_);
CREATE INDEX IDX_PROCESS_S1 ON T_BP_PROCESS (STATUS_, TYPE_);
ALTER TABLE T_BP_PROCESS COMMENT = '流程实体对象';

CREATE TABLE T_BP_COMMENT
(
    UIDPK_ VARCHAR(128) PRIMARY KEY NOT NULL,
    ROLE_ VARCHAR(64) DEFAULT NULL ,
    ROLE_ACT_ VARCHAR(64) DEFAULT NULL ,
    SYSTEM_ SMALLINT DEFAULT 0
);
CREATE INDEX IDX_COMMENT_SYS ON T_BP_COMMENT (SYSTEM_);
ALTER TABLE T_BP_COMMENT COMMENT = '流程备注实体对象';