CREATE TABLE T_BP_PROCESS
(
  UIDPK_ VARCHAR2(128) NOT NULL
, PROC_DEF_ID_ VARCHAR2(128) NOT NULL
, PROC_INST_ID_ VARCHAR2(128)
, STATUS_ VARCHAR2(16) NOT NULL
, TYPE_ VARCHAR2(64) NOT NULL
, CREATE_BY_ VARCHAR2(64) NOT NULL
, CREATE_TIME_ TIMESTAMP NOT NULL
, START_TIME_ TIMESTAMP
, END_TIME_ TIMESTAMP
, CONSTRAINT PK_PROCESS PRIMARY KEY
  (UIDPK_) ENABLE
);
CREATE INDEX IDX_PROCESS_ID ON T_BP_PROCESS (PROC_INST_ID_);
CREATE INDEX IDX_PROCESS_S1 ON T_BP_PROCESS (STATUS_, TYPE_);
ALTER TABLE T_BP_PROCESS COMMENT = '流程实体对象';

CREATE TABLE T_BP_COMMENT
(
  UIDPK_ VARCHAR2(128) NOT NULL
, ROLE_ VARCHAR2(64)
, ROLE_ACT_ VARCHAR2(20)
, SYSTEM_ SMALLINT DEFAULT 0
, CONSTRAINT PK_COMMENT PRIMARY KEY
  (UIDPK_)ENABLE
);

CREATE INDEX IDX_COMMENT_SYS ON T_BP_COMMENT (SYSTEM_);
ALTER TABLE T_BP_COMMENT COMMENT = '流程备注实体对象';